# Generated by Django 5.1.6 on 2025-02-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactscore', '0001_initial_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_book',
        ),
    ]
