# Generated by Django 5.1.6 on 2025-02-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactscore', '0002_contact_photo_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
