# Generated by Django 5.1.6 on 2025-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactscore', '0003_contact_phone_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
