# Generated by Django 5.1.6 on 2025-02-23 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactscore', '0004_contacts_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email address.')]),
        ),
    ]
